# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               UNALog
tagline:             ''
description:         'UNALog'
url:                 https://unalog.github.io/
baseurl:             ''

# About/contact
author:
  name:              UNA
  url:               https://unalog.github.io/
  email:             una0085@gmail.com

# Custom vars
version:             1.0.0


gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num"

